DROP TABLE IF EXISTS attend;

CREATE TABLE attend (
  id SERIAL PRIMARY KEY,
  children INTEGER NOT NULL,
  guest INTEGER REFERENCES users(id) ON DELETE SET NULL,
  event INTEGER REFERENCES events(id) ON DELETE SET NULL
); 